# Generated by Django 5.1.7 on 2025-04-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='next_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='category',
            field=models.CharField(choices=[('exercises', 'Exercises'), ('nutrition', 'Nutrition')], max_length=20),
        ),
    ]
