# Generated by Django 5.1.7 on 2025-04-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_subscriptionplan_next_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='duration_months',
            new_name='duration_weeks',
        ),
    ]
