# Generated by Django 5.1.7 on 2025-04-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_planday_remove_subscriptionplan_plan_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlanDay',
            new_name='Day',
        ),
        migrations.RenameModel(
            old_name='PlanWeek',
            new_name='Week',
        ),
    ]
