# Generated by Django 5.1.7 on 2025-05-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_subscriptionplan_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='level',
            field=models.CharField(choices=[('1_beginner', 'Beginner'), ('2_intermediate', 'Intermediate'), ('3_advanced', 'Advanced'), ('4_pro', 'Pro')], max_length=20),
        ),
    ]
