# Generated by Django 5.1.7 on 2025-05-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_alter_subscriptionplan_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DayContentItemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('day_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='plans.daysnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_weeks', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('level', models.IntegerField()),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('original_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='WeekSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('plan_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='plans.subscriptionplansnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='daysnapshot',
            name='week_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='plans.weeksnapshot'),
        ),
    ]
