# Generated by Django 5.1.7 on 2025-05-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_remove_subscriptionlineitem_plan_snapshot_and_more'),
        ('plans', '0010_daysnapshot_daycontentitemsnapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daysnapshot',
            name='week_snapshot',
        ),
        migrations.RemoveField(
            model_name='subscriptionplansnapshot',
            name='original_plan',
        ),
        migrations.RemoveField(
            model_name='weeksnapshot',
            name='plan_snapshot',
        ),
        migrations.DeleteModel(
            name='DayContentItemSnapshot',
        ),
        migrations.DeleteModel(
            name='DaySnapshot',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlanSnapshot',
        ),
        migrations.DeleteModel(
            name='WeekSnapshot',
        ),
    ]
