# Generated by Django 5.1.7 on 2025-05-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymessage',
            name='avatar',
            field=models.URLField(default='/media/avatars/default_avatar.jpg'),
        ),
    ]
