# Generated by Django 5.1.7 on 2025-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_communitypost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communitymessage",
            name="avatar",
            field=models.URLField(default="avatars/default_avatar.jpg"),
        ),
    ]
