# Generated by Django 5.1.7 on 2025-05-12 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_subscription'),
        ('plans', '0009_alter_subscriptionplan_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_sid',
            new_name='stripe_pid',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plans.subscriptionplan'),
        ),
    ]
