# Generated by Django 5.1.7 on 2025-05-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_stripe_sid_subscription_stripe_pid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
