# Generated by Django 5.1.7 on 2025-05-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_rename_start_date_subscription_date_and_more'),
        ('profiles', '0004_userprofile_email_userprofile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='profiles.userprofile'),
        ),
    ]
