# Generated by Django 5.1.7 on 2025-05-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_alter_subscription_user_profile'),
        ('plans', '0010_daysnapshot_daycontentitemsnapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionlineitem',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='plan_snapshot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='plans.subscriptionplansnapshot'),
        ),
    ]
