# Generated by Django 5.1.7 on 2025-05-19 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_remove_subscriptionlineitem_plan_and_more'),
        ('plans', '0010_daysnapshot_daycontentitemsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlineitem',
            name='plan_snapshot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.subscriptionplansnapshot'),
        ),
    ]
