# Generated by Django 5.1.7 on 2025-05-19 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_alter_subscriptionlineitem_plan_snapshot'),
        ('plans', '0010_daysnapshot_daycontentitemsnapshot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionlineitem',
            name='plan_snapshot',
        ),
        migrations.AddField(
            model_name='subscriptionlineitem',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.subscriptionplan'),
        ),
    ]
