# Generated by Django 5.1.7 on 2025-05-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='plan',
            new_name='product',
        ),
    ]
